version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Mongo Express UI
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo_db

  # Node api service
  api:
    image: nodeapp
    container_name: nodeapp_container
    ports:
      - 3030:3030
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
